<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amazon_field-keywords</name>
   <tag></tag>
   <elementGuidId>59567c44-3088-40bb-81cd-756fe6fec329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-bb-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-bb-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f041fc0f-4978-4f74-a4aa-d921ad29c828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9aa2adb9-0fec-4605-9afc-0496666be48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-bb-search</value>
      <webElementGuid>476b6d9e-bfcd-4430-a1e5-84dac514b46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search For</value>
      <webElementGuid>71e4b805-df4b-48cd-bd61-3760ef7f5cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field-keywords</value>
      <webElementGuid>a7f3dd23-3ed8-4b23-a5c2-01ec62180f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>986250d4-0077-4b5c-a668-c45bbbf0c832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-bb-search&quot;)</value>
      <webElementGuid>8b38ebdd-8021-42c5-b0a2-ef64245bc52c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-bb-search']</value>
      <webElementGuid>e8bb4346-1667-49fb-aa80-28fe8cc83ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-bb-searchbar']/form/div/div/input</value>
      <webElementGuid>cd0b7292-c20e-4d12-a30b-bb4d16920f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b6b9dcf5-ad6e-4099-b0a5-378a9c79958f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nav-bb-search' and @title = 'Search For' and @name = 'field-keywords']</value>
      <webElementGuid>9a3bcd88-3f78-4247-a995-8ff903fd8911</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
